### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by AdventurerRussia** [snylonue/mpv_slicing_copy#3]
I press c and set the placemarks, but then nothing happens. I have FFmpeg installed and another script uses it, but your script doesn't see it.
maybe you should make a separate keyboard shortcut to start encoding?

**Comment by snylonue** [comment]
Please provide a log file

Did you create a `cutfragments` folder in mpv's config dir as the README says?

**Comment by snylonue** [comment]
> Press c first time to mark the start of the fragment. Press it again to mark the end of the fragment and write it to the disk. 

you should press `c` again to set where the fragment ends
