### ISSUE TITLE
Running script on mpv.net

### ISSUE THREAD

**Issue by drcorg** [snylonue/mpv_slicing_copy#4]
Hi, I'm trying to run your script with mpv.net but the key binds don't seem to overwrite the ones in mpv.net.  I've tried deleting the lines with the relevant binds in input.conf, but it just results in a no key bindings error when checking the console. Any help? the script runs fine on regular mpv.

**Comment by snylonue** [comment]
Sorry for the delay.

It seems due to stax76/mpv.net#271
